### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by dmikushin** [n-eiling/cuda-fatbin-decompression#1]
Thank you for working on this! My best guess was that PTX compression is done with something similar to LZOP algorithm. I was sure someone with eagle eye in LZ topic would be able to tell exactly. Now you demystified this!

**Comment by n-eiling** [comment]
Thanks! Just as a note: I think my decompression still has some issues in certain situation (especially very large kernels). Ideally I would use some standard LZ4 algorithm instead of reinventing the wheel.
Also note that I was mostly interested in decompression SASS and specifically not PTX - or really I am only interested in the fatbin header that contains the kernel metadata.

**Comment by dmikushin** [comment]
Thank you for mentioning this! We need PTX decompression for https://github.com/gpuocelot/gpuocelot
